# Generated by Django 5.2.9 on 2025-12-30 03:47

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("appointments", "__first__"),
        ("clinic", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "color",
                    models.CharField(
                        default="#6B7280",
                        help_text="Color para identificación visual",
                        max_length=7,
                        verbose_name="color",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="box-seam",
                        help_text="Nombre del icono Bootstrap Icons",
                        max_length=50,
                        verbose_name="icono",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="orden")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
            ],
            options={
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nombre")),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="contacto"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="correo electrónico"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="dirección")),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
            ],
            options={
                "verbose_name": "proveedor",
                "verbose_name_plural": "proveedores",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Código interno o SKU",
                        max_length=50,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="nombre")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="marca"),
                ),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("unit", "Unidad"),
                            ("box", "Caja"),
                            ("pack", "Paquete"),
                            ("tube", "Tubo"),
                            ("bottle", "Frasco"),
                            ("ml", "Mililitros"),
                            ("gr", "Gramos"),
                            ("kit", "Kit"),
                        ],
                        default="unit",
                        max_length=20,
                        verbose_name="unidad de medida",
                    ),
                ),
                (
                    "current_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="stock actual",
                    ),
                ),
                (
                    "minimum_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=5,
                        help_text="Alerta cuando el stock sea igual o menor",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="stock mínimo",
                    ),
                ),
                (
                    "maximum_stock",
                    models.DecimalField(
                        decimal_places=2,
                        default=100,
                        help_text="Cantidad máxima recomendada",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="stock máximo",
                    ),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="precio de compra",
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Precio si se vende al paciente",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                        verbose_name="precio de venta",
                    ),
                ),
                (
                    "expiration_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="fecha de vencimiento"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Estante A, Gaveta 3",
                        max_length=100,
                        verbose_name="ubicación",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="actualizado"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products",
                        to="inventory.category",
                        verbose_name="categoría",
                    ),
                ),
                (
                    "clinic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="clinic.clinic",
                        verbose_name="consultorio",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="inventory.supplier",
                        verbose_name="proveedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("in", "Entrada"),
                            ("out", "Salida"),
                            ("adjustment", "Ajuste"),
                            ("return", "Devolución"),
                            ("expired", "Vencido"),
                            ("damaged", "Dañado"),
                        ],
                        max_length=20,
                        verbose_name="tipo",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="cantidad",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="costo unitario",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Uso en procedimiento, Compra, Pérdida",
                        max_length=100,
                        verbose_name="motivo",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="fecha"),
                ),
                (
                    "appointment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to="appointments.appointment",
                        verbose_name="cita",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="registrado por",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.product",
                        verbose_name="producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "movimiento de stock",
                "verbose_name_plural": "movimientos de stock",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["code"], name="inventory_p_code_a06c9c_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "is_active"], name="inventory_p_categor_471092_idx"
            ),
        ),
    ]
